language: python
sudo: false
dist: trusty
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - REQ="Django>=1.9,<1.10 django-mptt"
  - REQ="Django>=1.10,<1.11 django-mptt-nomagic"
install:
  - pip install -U pip wheel setuptools
  - pip install $REQ coverage flake8 pytz
script: "python testapp/runtests.py && flake8 ."
