language: python
sudo: false
python:
  - "2.7"
  - "3.4"
env:
  - REQ="Django>=1.9,<1.10 django-mptt"
  - REQ="https://github.com/django/django/archive/master.zip django-mptt"
install:
  - pip install $REQ flake8
  - python setup.py -q install
script: "cd tests && ./manage.py test testapp && flake8 ."
