language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - REQ="Django>=1.9,<1.10"
  - REQ="https://github.com/django/django/archive/master.zip"
matrix:
  exclude:
# Avoid "UnicodeEncodeError: 'ascii' codec can't encode character u'\u2297' in
# position 60: ordinal not in range(128)" ???
    - python: "2.7"
      env: REQ="https://github.com/django/django/archive/master.zip"
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip"
install:
  - pip install $REQ coverage django-mptt flake8 pytz
script: "python testapp/runtests.py && flake8 ."
